name: linting

# only run this workflow on new commits to master
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name: ${{ matrix.task }}
    runs-on: macos-latet
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: lint-dockerfile
    steps:
      - name: checkout repository
        uses: actions/checkout@v1
      - name: lint dockerfile
        shell: bash
        run: |
          brew upgrade
          brew install hadolint
          hadolint Dockerfile
